package proyecto.interfaces;

import java.awt.Color;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyecto.clases.*;

public class ClienteConfCompra extends javax.swing.JFrame {

    private Cliente cliente;
    private Producto producto;
    private JFrame principal;
    private Manejador manejadorDolar = new ManejadorMonedaDolar();
    private Manejador manejadorEuro = new ManejadorMonedaEuro();
    private Manejador manejadorOtro = new ManejadorMonedaOtro();
    private Dolar precioFinalDolares;
    private Servidor proxy = new Proxy(new ServidorBBDD());
    public ClienteConfCompra(JFrame v, Cliente c, Producto p) {
        initComponents();
        principal = v;
        principal.setVisible(false);
        this.setVisible(true);
        cliente = c;
        producto = p;
        manejadorDolar.setSucesor(manejadorEuro);
        manejadorEuro.setSucesor(manejadorOtro);
        jLabelNombreProducto.setText("Producto: " + producto.getNombre());
        precioFinalDolares = producto.getPrecio();
        jLabelPrecioActual.setText("Precio actual:" + manejadorDolar.calcularPrecio(precioFinalDolares, cliente));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreProducto = new javax.swing.JLabel();
        jLabelPrecioActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonUsarCodigos = new javax.swing.JButton();
        jButtonConfirmarCompra = new javax.swing.JButton();
        jLabelSaldoError = new javax.swing.JLabel();
        jLabelErrorCodigos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLibreria = new javax.swing.JMenuItem();
        jMenuItemLlavero = new javax.swing.JMenuItem();
        jMenuItemSaldo = new javax.swing.JMenuItem();
        jMenuItemTienda = new javax.swing.JMenuItem();
        jMenuItemNotificacion = new javax.swing.JMenuItem();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNombreProducto.setText("jLabel1");

        jLabelPrecioActual.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Códigos Descuento");

        jButtonUsarCodigos.setText("Usar Códigos");
        jButtonUsarCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsarCodigosActionPerformed(evt);
            }
        });

        jButtonConfirmarCompra.setText("Confirmar Compra");
        jButtonConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarCompraActionPerformed(evt);
            }
        });

        jMenu1.setText("Menú");

        jMenuItemLibreria.setText("Librería");
        jMenuItemLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibreriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLibreria);

        jMenuItemLlavero.setText("Llavero");
        jMenuItemLlavero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLlaveroActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLlavero);

        jMenuItemSaldo.setText("Saldo");
        jMenuItemSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaldoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSaldo);

        jMenuItemTienda.setText("Tienda");
        jMenuItemTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTiendaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTienda);

        jMenuItemNotificacion.setText("Notificaciones");
        jMenuItemNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotificacionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNotificacion);

        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButtonConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabelSaldoError)))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreProducto)
                    .addComponent(jLabelPrecioActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelErrorCodigos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1)
                        .addComponent(jButtonUsarCodigos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombreProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrecioActual))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUsarCodigos)
                .addGap(18, 18, 18)
                .addComponent(jLabelErrorCodigos)
                .addGap(24, 24, 24)
                .addComponent(jButtonConfirmarCompra)
                .addGap(18, 18, 18)
                .addComponent(jLabelSaldoError)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsarCodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsarCodigosActionPerformed
        String[] codigos = jTextArea1.getText().split("\n");
        double descuentoTotal = 0;
        boolean aplicables = true;
        for (String c: codigos)
        {
            if (cliente.getCodigoFromLlavero(c) == null || (cliente.getCodigoFromLlavero(c) != null && 
                    !cliente.getCodigoFromLlavero(c).getProducto().getNombre().equals(producto.getNombre())) )
            {
                aplicables = false;
            }
            else 
            {
                descuentoTotal += cliente.getCodigoFromLlavero(c).getCantidad();
            }
        }
        if (!aplicables)
        {
            jLabelErrorCodigos.setText("Uno de los códigos no es correcto .");
            jLabelErrorCodigos.setForeground(Color.red);
        }
        else if (descuentoTotal > 1)
        {
            jLabelErrorCodigos.setText("El descuento excede el 100%");
            jLabelErrorCodigos.setForeground(Color.red);
        }
        else
        {
            jLabelErrorCodigos.setText("");
            jButtonUsarCodigos.setVisible(false);
            precioFinalDolares = new Dolar(precioFinalDolares.getCantidad() * (1 - descuentoTotal));
            jLabelPrecioActual.setText("Precio actual:" + manejadorDolar.calcularPrecio(precioFinalDolares, cliente));
            
        }
    }//GEN-LAST:event_jButtonUsarCodigosActionPerformed

    private void jMenuItemLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibreriaActionPerformed
        ClienteLibreria c = new ClienteLibreria(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemLibreriaActionPerformed

    private void jMenuItemLlaveroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLlaveroActionPerformed
        ClienteLlavero c = new ClienteLlavero(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemLlaveroActionPerformed

    private void jMenuItemSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaldoActionPerformed
        ClienteSaldo c = new ClienteSaldo(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemSaldoActionPerformed

    private void jMenuItemTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTiendaActionPerformed
        Tienda c = new Tienda(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemTiendaActionPerformed

    private void jMenuItemNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotificacionActionPerformed
        ClienteNotificaciones c = new ClienteNotificaciones(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemNotificacionActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        Inicio inicio = new Inicio();
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jButtonConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarCompraActionPerformed
        if (cliente.getSaldo() < manejadorDolar.calcularPrecio(precioFinalDolares, cliente)) {
            jLabelSaldoError.setText("Saldo insuficiente");
            jLabelSaldoError.setForeground(Color.red);
        }
        else
        {
            jLabelSaldoError.setText("");
            Factura factura = new Factura(cliente, producto, LocalDate.now(), precioFinalDolares);
            try {
                factura.imprimirFactura();
            } catch (IOException ex) {
                Logger.getLogger(ClienteConfCompra.class.getName()).log(Level.SEVERE, null, ex);
            }
            proxy.addFactura(factura);
            proxy.guardarFacturas();
            cliente.addProducto(producto);
            cliente.setSaldo(cliente.getSaldo() - manejadorDolar.calcularPrecio(precioFinalDolares, cliente));
            if (!jTextArea1.getText().equals(""))
            {
                String[] codigos = jTextArea1.getText().split("\n");
                for (String c: codigos)
                {
                    cliente.removeCodigo(cliente.getLlavero().indexOf(cliente.getCodigoFromLlavero(c)));
                }
            }
            proxy.guardarClientes();
            JOptionPane.showMessageDialog(this, "Se ha añadido el producto a su librería y se ha generado la factura.");
            Tienda c = new Tienda(this, cliente);
            c.setLocationRelativeTo(null);
            c.setVisible(true); 
        }
    }//GEN-LAST:event_jButtonConfirmarCompraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarCompra;
    private javax.swing.JButton jButtonUsarCodigos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelErrorCodigos;
    private javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JLabel jLabelPrecioActual;
    private javax.swing.JLabel jLabelSaldoError;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemLibreria;
    private javax.swing.JMenuItem jMenuItemLlavero;
    private javax.swing.JMenuItem jMenuItemNotificacion;
    private javax.swing.JMenuItem jMenuItemSaldo;
    private javax.swing.JMenuItem jMenuItemTienda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
