/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.interfaces;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JFrame;
import proyecto.clases.Creador;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import proyecto.clases.*;

/**
 *
 * @author diego
 */
public class CreadorModificacion extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    private Servidor proxy = new Proxy(new ServidorBBDD());
    private JFrame principal;
    private Creador creador;
    private Producto producto;
    private String clase;
    private String nombreImagen, rutaImagen, extension = "jpg";
    private BufferedImage bimage;
    private File file;
    private LecturaBBDD lectura = new LecturaBBDD(proxy.getVideojuegos(), proxy.getProductividad(), proxy.getAntivirus());
    String codigoInternoProducto;

    public CreadorModificacion(JFrame v, Creador c, Object o, String clase) {
        initComponents();
        
        principal = v;
        principal.setVisible(false);
        this.setVisible(true);
        creador = c;
        this.clase = clase;
        
        moldearPagina(clase);

        cargarInformacion(o, clase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonModificarNombre = new javax.swing.JButton();
        jButtonjLabel9 = new javax.swing.JButton();
        jButtonDescripcion = new javax.swing.JButton();
        jButtonPrecio = new javax.swing.JButton();
        jButtonCaratula = new javax.swing.JButton();
        jButtonLimitaciones = new javax.swing.JButton();
        jButtonjLabel8 = new javax.swing.JButton();
        jButtonjLabel10 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CREADOR");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Limitaciones técnicas:");

        jLabel6.setText("Carátula:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel8.setText("Versión actual:");

        jLabel9.setText("Tipo:");

        jLabel10.setText("Jugadores:");

        jCheckBox1.setText("Multijugador");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Online");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de Producto:");

        jLabel13.setText("Tipo de Producto");

        jButtonModificarNombre.setText("Modificar");
        jButtonModificarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarNombreActionPerformed(evt);
            }
        });

        jButtonjLabel9.setText("Modificar");
        jButtonjLabel9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjLabel9ActionPerformed(evt);
            }
        });

        jButtonDescripcion.setText("Modificar");
        jButtonDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescripcionActionPerformed(evt);
            }
        });

        jButtonPrecio.setText("Modificar");
        jButtonPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrecioActionPerformed(evt);
            }
        });

        jButtonCaratula.setText("Modificar");
        jButtonCaratula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaratulaActionPerformed(evt);
            }
        });

        jButtonLimitaciones.setText("Modificar");
        jButtonLimitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimitacionesActionPerformed(evt);
            }
        });

        jButtonjLabel8.setText("Modificar");
        jButtonjLabel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjLabel8ActionPerformed(evt);
            }
        });

        jButtonjLabel10.setText("Modificar");
        jButtonjLabel10.setToolTipText("");
        jButtonjLabel10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjLabel10ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menú");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Información");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Principal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Cerrar Sesión");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(465, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(362, 362, 362))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField1)
                            .addComponent(jTextField3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModificarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonjLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCaratula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonjLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonjLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificarNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDescripcion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPrecio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButtonCaratula))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLimitaciones))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonjLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonjLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonjLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2))
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moldearPagina(String clase) {
        switch (clase) {
            case "Videojuego" -> {
                jLabel13.setText("Videojuego");
                jLabel8.setText("Géneros:");
                jLabel9.setText("Otras plataformas:");
            }
            case "Productividad" -> {
                jLabel13.setText("Productividad");
                jLabel8.setText("Versión actual:");
                jLabel9.setText("Tipo:");
                jLabel10.setVisible(false);
                jTextField5.setVisible(false);
                jCheckBox1.setVisible(false);
                jCheckBox2.setVisible(false);
                jLabel9.setText("Tipo:");
                jButtonjLabel10.setVisible(false);
            }
            case "Antivirus" -> {
                jLabel13.setText("Antivirus");
                jLabel8.setText("Versión actual:");
                jLabel9.setText("Tipo:");
                jLabel10.setVisible(false);
                jTextField5.setVisible(false);
                jCheckBox1.setVisible(false);
                jCheckBox2.setVisible(false);
                jLabel9.setText("Certificados:");
                jButtonjLabel10.setVisible(false);
            }
        }
    }

    private void cargarInformacion(Object o, String clase) {
        switch (clase) {
            case "Videojuego" -> {
                Videojuego v = (Videojuego) o;
                producto = v;
                jTextField1.setText(v.getNombre());
                jTextArea1.setText(v.getDescripcion());
                jTextField3.setText(String.valueOf(v.getPrecio().getCantidad()));
                jTextField6.setText(v.getCaratula());
                cargarImagen(v.getCaratula());
                nombreImagen = v.getCaratula();
                jTextArea2.setText(mostrarListaComoString(v.getLimitacionesTecnicas()));
                jTextField2.setText(mostrarListaComoString(v.getGeneros()));
                jTextField4.setText(mostrarListaComoString(v.getOtrasPlataformas()));
                jTextField5.setText(String.valueOf(v.getJugadores()));
                jCheckBox1.setSelected(v.isMultijugador());
                jCheckBox2.setSelected(v.isOnline());
                codigoInternoProducto = v.getCondigoInterno();
            }
            case "Productividad" -> {
                Productividad p = (Productividad) o;
                producto = p;
                jTextField1.setText(p.getNombre());
                jTextArea1.setText(p.getDescripcion());
                jTextField3.setText(String.valueOf(p.getPrecio().getCantidad()));
                jTextField6.setText(p.getCaratula());
                cargarImagen(p.getCaratula());
                nombreImagen = p.getCaratula();
                jTextArea2.setText(mostrarListaComoString(p.getLimitacionesTecnicas()));
                jTextField2.setText(p.getVersionActual());
                jTextField4.setText(p.getTipo());
                codigoInternoProducto = p.getCondigoInterno();
            }
            case "Antivirus" -> {
                Antivirus a = (Antivirus) o;
                producto = a;
                jTextField1.setText(a.getNombre());
                jTextArea1.setText(a.getDescripcion());
                jTextField3.setText(String.valueOf(a.getPrecio().getCantidad()));
                jTextField6.setText(a.getCaratula());
                cargarImagen(a.getCaratula());
                nombreImagen = a.getCaratula();
                jTextArea2.setText(mostrarListaComoString(a.getLimitacionesTecnicas()));
                jTextField2.setText(a.getVersionActual());
                jTextField4.setText(mostrarListaComoString(a.getCertificaciones()));
                codigoInternoProducto = a.getCondigoInterno();
            }
        }
    }

    private void cargarImagen(String nombreImagen) {
        String rutaImagen = "./portadas/" + nombreImagen;
        ImageIcon portada_original = new ImageIcon(rutaImagen);
        ImageIcon portada_img = new ImageIcon(portada_original.getImage().getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), java.awt.Image.SCALE_SMOOTH));
        jLabel12.setIcon(portada_img);
    }

    private String mostrarListaComoString(ArrayList lista) {
        String cadena = "";
        
        for (int i = 0; i < lista.size() - 1; i++) {
            cadena += lista.get(i) + ", ";
        }

        cadena += lista.get(lista.size() - 1);

        return cadena;
    }

    private ArrayList<String> procesarString(String texto) {
        ArrayList<String> lista = new ArrayList<>();

        String[] partes = texto.split(", ");

        for (String parte : partes) {
            lista.add(parte);
        }

        return lista;
    }

    private boolean esDouble(String numero) {
        Pattern pat = Pattern.compile("^[0-9]{1,20}\\.[0-9]{2}$");
        Matcher mat = pat.matcher(numero);
        if (mat.find()) {
            return mat.group().equals(numero);
        } else {
            return false;
        }
    }

    private boolean esInteger(String numero) {
        Pattern pat = Pattern.compile("^[1-9]{1}[0-9]{0,20}$");
        Matcher mat = pat.matcher(numero);
        if (mat.find()) {
            return mat.group().equals(numero);
        } else {
            return false;
        }
    }

    private void guardarImagen() {
        String imagen = nombreImagen;
        if(!jLabel1.getText().equals("ADMIN")){
            if (jLabel12.getIcon() == null) { //SI NO HAY PORTADA
                JOptionPane.showMessageDialog(this, "Error: Falta portada.");
            } else {
            //Se guarda la imagen en la carpeta "portadas"
                try {
                    bimage = ImageIO.read(file);
                    File fout = new File("./portadas/" + imagen);
                    ImageIO.write(bimage, extension, fout);
                    JOptionPane.showMessageDialog(this, "Imagen guardada");
                } catch (IOException e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(this, "Error al guardar imagen");
                }
            } 
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            nombreImagen = file.getName();
            jTextField6.setText(rutaImagen);
            System.out.println("imagen: " + nombreImagen);
            String[] aux = nombreImagen.split("\\.");
        } else {
            JOptionPane.showMessageDialog(this, "Ningún fichero seleccionado", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }

        ImageIcon imagen = new ImageIcon(rutaImagen);
        //Se redimensiona
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), java.awt.Image.SCALE_SMOOTH));
        jLabel12.setIcon(imgRedimensionada);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonModificarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarNombreActionPerformed
        Comando comando = new ComandoCambiarNombre(proxy.getProductoByCodigo(codigoInternoProducto),jTextField1.getText());
        comando.ejecutar();
        proxy.guardarAntivirus();
        proxy.guardarClientes();
        proxy.guardarProductividad();
        proxy.guardarVideojuegos();
    }//GEN-LAST:event_jButtonModificarNombreActionPerformed

    private void jButtonjLabel9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjLabel9ActionPerformed
        switch (clase) {
            case "Productividad" -> {
                Comando comando = new ComandoCambiarTipo(proxy.getProductoByCodigo(codigoInternoProducto),jTextField4.getText());
                comando.ejecutar();
                proxy.guardarAntivirus();
                proxy.guardarClientes();
                proxy.guardarProductividad();
                proxy.guardarVideojuegos();
            }
            case "Antivirus" -> {
                Comando comando = new ComandoCambiarCertificaciones(proxy.getProductoByCodigo(codigoInternoProducto),procesarString(jTextField4.getText()));
                comando.ejecutar();
                proxy.guardarAntivirus();
                proxy.guardarClientes();
                proxy.guardarProductividad();
                proxy.guardarVideojuegos();
            }
            case "Videojuego" -> {
                Comando comando = new ComandoCambiarOtrasPlataformas(proxy.getProductoByCodigo(codigoInternoProducto),procesarString(jTextField4.getText()));
                comando.ejecutar();
                proxy.guardarAntivirus();
                proxy.guardarClientes();
                proxy.guardarProductividad();
                proxy.guardarVideojuegos();
            }
        }
    }//GEN-LAST:event_jButtonjLabel9ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        Comando comando = new ComandoCambiarMultijugador(proxy.getProductoByCodigo(codigoInternoProducto),jCheckBox1.isSelected());
        comando.ejecutar();
        proxy.guardarAntivirus();
        proxy.guardarClientes();
        proxy.guardarProductividad();
        proxy.guardarVideojuegos();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        Comando comando = new ComandoCambiarOnline(proxy.getProductoByCodigo(codigoInternoProducto),jCheckBox2.isSelected());
        comando.ejecutar();
        proxy.guardarAntivirus();
        proxy.guardarClientes();
        proxy.guardarProductividad();
        proxy.guardarVideojuegos();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButtonDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescripcionActionPerformed
        Comando comando = new ComandoCambiarDescripcion(proxy.getProductoByCodigo(codigoInternoProducto),jTextArea1.getText());
        comando.ejecutar();
        proxy.guardarAntivirus();
        proxy.guardarClientes();
        proxy.guardarProductividad();
        proxy.guardarVideojuegos();
    }//GEN-LAST:event_jButtonDescripcionActionPerformed

    private void jButtonPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrecioActionPerformed
        if (esDouble(jTextField3.getText()))
        {
            Comando comando = new ComandoCambiarPrecio(proxy.getProductoByCodigo(codigoInternoProducto),new Dolar(Double.parseDouble(jTextField3.getText())));
            comando.ejecutar();
            proxy.guardarAntivirus();
            proxy.guardarClientes();
            proxy.guardarProductividad();
            proxy.guardarVideojuegos();
        }
    }//GEN-LAST:event_jButtonPrecioActionPerformed

    private void jButtonCaratulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaratulaActionPerformed
        int ultimaAparicion = jTextField6.getText().lastIndexOf('\\');
        String subcadena = jTextField6.getText().substring(ultimaAparicion + 1);
        Comando comando = new ComandoCambiarCaratula(proxy.getProductoByCodigo(codigoInternoProducto),subcadena);
        comando.ejecutar();
        proxy.guardarAntivirus();
        proxy.guardarClientes();
        proxy.guardarProductividad();
        proxy.guardarVideojuegos();
        guardarImagen();
    }//GEN-LAST:event_jButtonCaratulaActionPerformed

    private void jButtonLimitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimitacionesActionPerformed
        Comando comando = new ComandoCambiarLimitaciones(proxy.getProductoByCodigo(codigoInternoProducto),procesarString(jTextArea2.getText()));
        comando.ejecutar();
        proxy.guardarAntivirus();
        proxy.guardarClientes();
        proxy.guardarProductividad();
        proxy.guardarVideojuegos();
    }//GEN-LAST:event_jButtonLimitacionesActionPerformed

    private void jButtonjLabel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjLabel8ActionPerformed
        switch (clase) {
            case "Productividad" -> {
                Comando comando = new ComandoCambiarVersionActual(proxy.getProductoByCodigo(codigoInternoProducto),jTextField2.getText());
                comando.ejecutar();
                proxy.guardarAntivirus();
                proxy.guardarClientes();
                proxy.guardarProductividad();
                proxy.guardarVideojuegos();
            }
            case "Antivirus" -> {
                Comando comando = new ComandoCambiarVersionActual(proxy.getProductoByCodigo(codigoInternoProducto),jTextField2.getText());
                comando.ejecutar();
                proxy.guardarAntivirus();
                proxy.guardarClientes();
                proxy.guardarProductividad();
                proxy.guardarVideojuegos();
            }
            case "Videojuego" -> {
                Comando comando = new ComandoCambiarGeneros(proxy.getProductoByCodigo(codigoInternoProducto),procesarString(jTextField2.getText()));
                comando.ejecutar();
                proxy.guardarAntivirus();
                proxy.guardarClientes();
                proxy.guardarProductividad();
                proxy.guardarVideojuegos();
            }
        }
    }//GEN-LAST:event_jButtonjLabel8ActionPerformed

    private void jButtonjLabel10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjLabel10ActionPerformed
        if (esInteger(jTextField5.getText())) {
            Comando comando = new ComandoCambiarJugadores(proxy.getProductoByCodigo(codigoInternoProducto),Integer.parseInt(jTextField5.getText()));
            comando.ejecutar();
            proxy.guardarAntivirus();
            proxy.guardarClientes();
            proxy.guardarProductividad();
            proxy.guardarVideojuegos();
        }
    }//GEN-LAST:event_jButtonjLabel10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CreadorCreacion cc = new CreadorCreacion(this, creador);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CreadorInformacion ci = new CreadorInformacion(this, creador);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CreadorStatus cS = new CreadorStatus(this, creador);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Inicio inicio = new Inicio();
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCaratula;
    private javax.swing.JButton jButtonDescripcion;
    private javax.swing.JButton jButtonLimitaciones;
    private javax.swing.JButton jButtonModificarNombre;
    private javax.swing.JButton jButtonPrecio;
    private javax.swing.JButton jButtonjLabel10;
    private javax.swing.JButton jButtonjLabel8;
    private javax.swing.JButton jButtonjLabel9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
