/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.interfaces;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JFrame;
import proyecto.clases.Creador;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import proyecto.clases.*;

/**
 *
 * @author diego
 */
public class CreadorModificacion extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    private Servidor proxy = new Proxy(new ServidorBBDD());
    private JFrame principal;
    private Creador creador;
    private Producto producto;
    private String clase;
    private String nombreImagen, rutaImagen, extension = "jpg";
    private BufferedImage bimage;
    private File file;

    public CreadorModificacion(JFrame v, Creador c, Object o, String clase) {
        initComponents();

        principal = v;
        principal.setVisible(false);
        this.setVisible(true);
        creador = c;
        this.clase = clase;

        moldearPagina(clase);

        cargarInformacion(o, clase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CREADOR");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Limitaciones técnicas:");

        jLabel6.setText("Carátula:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel8.setText("Versión actual:");

        jLabel9.setText("Tipo:");

        jLabel10.setText("Jugadores:");

        jCheckBox1.setText("Multijugador");

        jCheckBox2.setText("Online");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Errores");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de Producto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(362, 362, 362))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moldearPagina(String clase) {
        switch (clase) {
            case "Videojuego" -> {
                jLabel13.setText("Videojuego");
                jLabel8.setText("Géneros:");
                jLabel9.setText("Otras plataformas:");
            }
            case "Productividad" -> {
                jLabel13.setText("Productividad");
                jLabel8.setText("Versión actual:");
                jLabel9.setText("Tipo:");
                jLabel10.setVisible(false);
                jTextField5.setVisible(false);
                jCheckBox1.setVisible(false);
                jCheckBox2.setVisible(false);
                jLabel9.setText("Tipo:");
            }
            case "Antivirus" -> {
                jLabel13.setText("Antivirus");
                jLabel8.setText("Versión actual:");
                jLabel9.setText("Tipo:");
                jLabel10.setVisible(false);
                jTextField5.setVisible(false);
                jCheckBox1.setVisible(false);
                jCheckBox2.setVisible(false);
                jLabel9.setText("Certificados:");
            }
        }
    }

    private void cargarInformacion(Object o, String clase) {
        switch (clase) {
            case "Videojuego" -> {
                Videojuego v = (Videojuego) o;
                producto = v;
                jTextField1.setText(v.getNombre());
                jTextArea1.setText(v.getDescripcion());
                jTextField3.setText(String.valueOf(v.getPrecio().getCantidad()));
                jTextField6.setText(v.getCaratula());
                cargarImagen(v.getCaratula());
                nombreImagen = v.getCaratula();
                jTextArea2.setText(mostrarListaComoString(v.getLimitacionesTecnicas()));
                jTextField2.setText(mostrarListaComoString(v.getGeneros()));
                jTextField4.setText(mostrarListaComoString(v.getOtrasPlataformas()));
                jTextField5.setText(String.valueOf(v.getJugadores()));
                jCheckBox1.setSelected(v.isMultijugador());
                jCheckBox2.setSelected(v.isOnline());
            }
            case "Productividad" -> {
                Productividad p = (Productividad) o;
                producto = p;
                jTextField1.setText(p.getNombre());
                jTextArea1.setText(p.getDescripcion());
                jTextField3.setText(String.valueOf(p.getPrecio().getCantidad()));
                jTextField6.setText(p.getCaratula());
                cargarImagen(p.getCaratula());
                nombreImagen = p.getCaratula();
                jTextArea2.setText(mostrarListaComoString(p.getLimitacionesTecnicas()));
                jTextField2.setText(p.getVersionActual());
                jTextField4.setText(p.getTipo());
            }
            case "Antivirus" -> {
                Antivirus a = (Antivirus) o;
                producto = a;
                jTextField1.setText(a.getNombre());
                jTextArea1.setText(a.getDescripcion());
                jTextField3.setText(String.valueOf(a.getPrecio().getCantidad()));
                jTextField6.setText(a.getCaratula());
                cargarImagen(a.getCaratula());
                nombreImagen = a.getCaratula();
                jTextArea2.setText(mostrarListaComoString(a.getLimitacionesTecnicas()));
                jTextField2.setText(a.getVersionActual());
                jTextField4.setText(mostrarListaComoString(a.getCertificaciones()));
            }
        }
    }

    private void cargarImagen(String nombreImagen) {
        String rutaImagen = "./portadas/" + nombreImagen;
        ImageIcon portada_original = new ImageIcon(rutaImagen);
        ImageIcon portada_img = new ImageIcon(portada_original.getImage().getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), java.awt.Image.SCALE_SMOOTH));
        jLabel12.setIcon(portada_img);
    }

    private String mostrarListaComoString(ArrayList lista) {
        String cadena = "";
        
        for (int i = 0; i < lista.size() - 1; i++) {
            cadena += lista.get(i) + ", ";
        }

        cadena += lista.get(lista.size() - 1);

        return cadena;
    }

    private ArrayList<String> procesarString(String texto) {
        ArrayList<String> lista = new ArrayList<>();

        String[] partes = texto.split(", ");

        for (String parte : partes) {
            lista.add(parte);
        }

        return lista;
    }

    private boolean esDouble(String numero) {
        Pattern pat = Pattern.compile("^[0-9]{1,20}\\.[0-9]{2}$");
        Matcher mat = pat.matcher(numero);
        if (mat.find()) {
            return mat.group().equals(numero);
        } else {
            return false;
        }
    }

    private boolean esInteger(String numero) {
        Pattern pat = Pattern.compile("^[1-9]{1}[0-9]{0,20}$");
        Matcher mat = pat.matcher(numero);
        if (mat.find()) {
            return mat.group().equals(numero);
        } else {
            return false;
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = jTextField1.getText();
        String codigoInterno = producto.getCondigoInterno();
        String descripcion = jTextArea1.getText();
        LocalDate fecha = producto.getFechaCreacion();
        String precio = jTextField3.getText();
        String valoracion = producto.getValoracionGeneral();
        ArrayList<Review> reviews = producto.getReviews();
        String limitacionesTecnicas = jTextArea2.getText();
        boolean aprobado = producto.isAprobado();

        switch (clase) {
            case "Videojuego" -> {
                String generos = jTextField2.getText();
                String otrasPlataformas = jTextField4.getText();
                String jugadores = jTextField5.getText();
                boolean multijugador = jCheckBox1.isSelected();
                boolean online = jCheckBox2.isSelected();

                if (!nombre.isEmpty() && !descripcion.isEmpty() && !limitacionesTecnicas.isEmpty()
                        && !generos.isEmpty() && !otrasPlataformas.isEmpty() && !jTextField6.getText().isEmpty() && esDouble(precio)
                        && esInteger(jugadores)) {
                    
                    if(!producto.getCaratula().equals(nombreImagen)){
                        guardarImagen();
                    }
                    Factoria fabrica = FactoriaConcreta.getInstanciaUnica();
                    Videojuego v = fabrica.crearProducto(procesarString(generos), procesarString(otrasPlataformas), multijugador,
                            Integer.parseInt(jugadores), online, nombre, codigoInterno, creador, descripcion, fecha, new Dolar(Double.parseDouble(precio)),
                            nombreImagen, valoracion, reviews, procesarString(limitacionesTecnicas), aprobado);
                    proxy.removeVideojuego(codigoInterno);
                    proxy.addVideojuego(v);
                    proxy.guardarVideojuegos();
                    this.setVisible(false);
                    principal.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Error: Rellena todos los campos.");
                }
            }
            case "Productividad" -> {
                String versionActual = jTextField2.getText();

                if (!nombre.isEmpty() && !descripcion.isEmpty() && !limitacionesTecnicas.isEmpty()
                        && !versionActual.isEmpty() && !jTextField4.getText().isEmpty() && !jTextField6.getText().isEmpty() && esDouble(precio)) {

                    if(!producto.getCaratula().equals(nombreImagen)){
                        guardarImagen();
                    }
                    Factoria fabrica = FactoriaConcreta.getInstanciaUnica();
                    Productividad p = fabrica.crearProducto(versionActual, LocalDate.now(), jTextField4.getText(), nombre, codigoInterno,
                            creador, descripcion, fecha, new Dolar(Double.parseDouble(precio)), nombreImagen,
                            valoracion, reviews, procesarString(limitacionesTecnicas), aprobado);
                    proxy.removeProductividad(codigoInterno);
                    proxy.addProductividad(p);
                    proxy.guardarProductividad();
                    jLabel11.setText("Productividad registrada");
                    jLabel11.setForeground(Color.green);
                    jLabel11.setVisible(true);
                    this.setVisible(false);
                    principal.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Error: Rellene todos los campos.");
                }
            }
            case "Antivirus" -> {
                String versionActual = jTextField2.getText();
                
                if (!nombre.isEmpty() && !descripcion.isEmpty() && !limitacionesTecnicas.isEmpty()
                        && !versionActual.isEmpty() && !jTextField4.getText().isEmpty() && !jTextField6.getText().isEmpty() && esDouble(precio)) {
                    if(!producto.getCaratula().equals(nombreImagen)){
                        guardarImagen();
                    }
                    Factoria fabrica = FactoriaConcreta.getInstanciaUnica();
                    Antivirus a = fabrica.crearProducto(versionActual, fecha, procesarString(jTextField4.getText()), nombre,
                            codigoInterno, creador, descripcion, fecha, new Dolar(Double.parseDouble(precio)), nombreImagen,
                            valoracion, reviews, procesarString(limitacionesTecnicas), aprobado);
                    proxy.removeAntivirus(codigoInterno);
                    proxy.addAntivirus(a);
                    proxy.guardarAntivirus();
                    jLabel11.setText("Antivirus registrado");
                    jLabel11.setForeground(Color.green);
                    jLabel11.setVisible(true);
                    this.setVisible(false);
                    principal.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Error: Rellene todos los campos.");
                }
            }

        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarImagen() {
        String imagen = nombreImagen;
        if (jLabel12.getIcon() == null) { //SI NO HAY PORTADA
            JOptionPane.showMessageDialog(this, "Error: Falta portada.");
        } else {
            //Se guarda la imagen en la carpeta "portadas"
            try {
                bimage = ImageIO.read(file);
                File fout = new File("./portadas/" + imagen);
                ImageIO.write(bimage, extension, fout);
                JOptionPane.showMessageDialog(this, "Imagen guardada");
            } catch (IOException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(this, "Error al guardar imagen");
            }
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            nombreImagen = file.getName();
            jTextField6.setText(rutaImagen);
            System.out.println("imagen: " + nombreImagen);
            String[] aux = nombreImagen.split("\\.");
        } else {
            JOptionPane.showMessageDialog(this, "Ningún fichero seleccionado", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }

        ImageIcon imagen = new ImageIcon(rutaImagen);
        //Se redimensiona
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(jLabel12.getWidth(), jLabel12.getHeight(), java.awt.Image.SCALE_SMOOTH));
        jLabel12.setIcon(imgRedimensionada);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
