
package proyecto.interfaces;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import proyecto.clases.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    private JFrame principal;
    private Cliente cliente;
    private Servidor proxy = new Proxy(new ServidorBBDD());
    private LecturaBBDD lectura = new LecturaBBDD(proxy.getVideojuegos(), proxy.getProductividad(), proxy.getAntivirus());
    private Estrategia estrategiaBusqueda;
    private Busqueda busqueda = new Busqueda(estrategiaBusqueda, new ArrayList<>());
    private DefaultTableModel mt = new DefaultTableModel();
    public Tienda(JFrame v, Cliente c) {
        initComponents();
        principal = v;
        principal.setVisible(false);
        this.setVisible(true);
        cliente = c;
        jComboBoxBusquedaCreador.setSelectedIndex(0);
        DefaultComboBoxModel creadores = new DefaultComboBoxModel (lectura.getListaCreadoresConProductos().toArray()); 
        jComboBoxBusquedaCreador.setModel(creadores);
        String[] ids = {"Nombre", "Creador", "Valoración", "Precio", "Tipo","Código Interno"};
        mt.setColumnIdentifiers(ids);
        jTableTienda.setModel(mt);
        for (Videojuego vj: lectura.getListaVideojuegos())
        {
            mt.addRow(new Object[]{vj.getNombre(), vj.getCreador().getCorreo(), vj.getValoracionGeneral(), vj.getPrecio(cliente), "Videojuego", vj.getCondigoInterno()});
        }
        for (Productividad pv: lectura.getListaProductividad())
        {
            mt.addRow(new Object[]{pv.getNombre(), pv.getCreador().getCorreo(), pv.getValoracionGeneral(), pv.getPrecio(cliente), "Productividad", pv.getCondigoInterno()});
        }
        for (Antivirus av: lectura.getListaAntivirus())
        {
            mt.addRow(new Object[]{av.getNombre(), av.getCreador().getCorreo(), av.getValoracionGeneral(), av.getPrecio(cliente), "Antivirus", av.getCondigoInterno()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextFieldBusquedaNombre = new javax.swing.JTextField();
        jComboBoxBusquedaCreador = new javax.swing.JComboBox<>();
        jComboBoxBusquedaValGeneral = new javax.swing.JComboBox<>();
        jSpinnerPrecioMinimo = new javax.swing.JSpinner();
        jSpinnerPrecioMaximo = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxCriterio = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTienda = new javax.swing.JTable();
        jButtonVerProducto = new javax.swing.JButton();
        jRadioButtonValoracion = new javax.swing.JRadioButton();
        jRadioButtonCreador = new javax.swing.JRadioButton();
        jRadioButtonNombre = new javax.swing.JRadioButton();
        jRadioButtonPrecioMinimo = new javax.swing.JRadioButton();
        jRadioButtonPrecioMaximo = new javax.swing.JRadioButton();
        jRadioButtonTipo = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLibreria = new javax.swing.JMenuItem();
        jMenuItemLlavero = new javax.swing.JMenuItem();
        jMenuItemSaldo = new javax.swing.JMenuItem();
        jMenuItemTienda = new javax.swing.JMenuItem();
        jMenuItemNotificacion = new javax.swing.JMenuItem();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxBusquedaCreador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxBusquedaValGeneral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muy Positiva", "Positiva", "Mixta", "Negativa", "Muy Negativa", "Sin Valorar" }));

        jSpinnerPrecioMinimo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jSpinnerPrecioMaximo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel6.setText("Criterio:");

        jComboBoxCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Al menos uno" }));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Videojuego", "Productividad", "Antivirus" }));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTableTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTienda);

        jButtonVerProducto.setText("Ver Producto");
        jButtonVerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerProductoActionPerformed(evt);
            }
        });

        jRadioButtonValoracion.setText("Valoración:");

        jRadioButtonCreador.setText("Creador:");

        jRadioButtonNombre.setText("Nombre:");

        jRadioButtonPrecioMinimo.setText("Precio mínimo:");

        jRadioButtonPrecioMaximo.setText("Precio Máximo:");

        jRadioButtonTipo.setText("Tipo:");

        jMenu1.setText("Menú");

        jMenuItemLibreria.setText("Librería");
        jMenuItemLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibreriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLibreria);

        jMenuItemLlavero.setText("Llavero");
        jMenuItemLlavero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLlaveroActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLlavero);

        jMenuItemSaldo.setText("Saldo");
        jMenuItemSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaldoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSaldo);

        jMenuItemTienda.setText("Tienda");
        jMenuItemTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTiendaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTienda);

        jMenuItemNotificacion.setText("Notificaciones");
        jMenuItemNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotificacionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNotificacion);

        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonPrecioMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerPrecioMinimo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButtonCreador))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPrecioMaximo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxBusquedaCreador, 0, 134, Short.MAX_VALUE)
                    .addComponent(jSpinnerPrecioMaximo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonValoracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxBusquedaValGeneral, 0, 140, Short.MAX_VALUE)
                    .addComponent(jComboBoxCriterio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jButtonVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jRadioButtonTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(471, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBusquedaCreador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBusquedaValGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonValoracion)
                    .addComponent(jRadioButtonCreador)
                    .addComponent(jRadioButtonNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerPrecioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPrecioMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonPrecioMinimo)
                    .addComponent(jRadioButtonPrecioMaximo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jRadioButtonTipo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVerProducto)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibreriaActionPerformed
        ClienteLibreria c = new ClienteLibreria(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemLibreriaActionPerformed

    private void jMenuItemLlaveroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLlaveroActionPerformed
        ClienteLlavero c = new ClienteLlavero(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemLlaveroActionPerformed

    private void jMenuItemSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaldoActionPerformed
        ClienteSaldo c = new ClienteSaldo(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemSaldoActionPerformed

    private void jMenuItemTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTiendaActionPerformed
        Tienda c = new Tienda(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemTiendaActionPerformed

    private void jMenuItemNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotificacionActionPerformed
        ClienteNotificaciones c = new ClienteNotificaciones(this, cliente);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemNotificacionActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        Inicio inicio = new Inicio();
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        LecturaBBDD nuevaLectura = new LecturaBBDD(lectura);
        ArrayList<Producto> listaInicial = new ArrayList<>();
        ArrayList<Producto> listaFinal = new ArrayList<>();
        for (Antivirus a: nuevaLectura.getListaAntivirus())
        {
            listaInicial.add(a);
        }
        for (Productividad p: nuevaLectura.getListaProductividad())
        {
            listaInicial.add(p);
        }
        for (Videojuego vj: nuevaLectura.getListaVideojuegos())
        {
            listaInicial.add(vj);
        }
        if(jComboBoxCriterio.getSelectedItem().toString().equals("Todos"))
        {
            String nombre = null;
            String creador = null; 
            String valoracion = null;
            Double precioMinimo = null;
            Double precioMaximo = null;
            String tipo = null; 
            if (jRadioButtonNombre.isSelected())
            {
                nombre = jTextFieldBusquedaNombre.getText();
            }
            if (jRadioButtonCreador.isSelected())
            {
                creador = (String) jComboBoxBusquedaCreador.getSelectedItem();
            }
            if (jRadioButtonValoracion.isSelected())
            {
                valoracion = (String) jComboBoxBusquedaValGeneral.getSelectedItem();
            }
            if (jRadioButtonPrecioMinimo.isSelected())
            {
                precioMinimo = (Double) jSpinnerPrecioMinimo.getValue();
            }
            if (jRadioButtonPrecioMaximo.isSelected())
            {
                precioMaximo = (Double) jSpinnerPrecioMaximo.getValue();
            }
            if (jRadioButtonTipo.isSelected())
            {
                tipo = (String) jComboBoxTipo.getSelectedItem();
            }
            estrategiaBusqueda = new EstrategiaBusquedaCompleta();
            busqueda.setEstrategia(estrategiaBusqueda);
            busqueda.setLista(listaInicial);
            listaFinal = busqueda.ejecutarEstrategia(nombre, creador, valoracion, precioMinimo, precioMaximo, tipo, cliente);
        }
        else
        {
            if (jRadioButtonNombre.isSelected())
            {
                String nombre = jTextFieldBusquedaNombre.getText();
                estrategiaBusqueda = new EstrategiaBusquedaNombre();
                busqueda.setEstrategia(estrategiaBusqueda);
                busqueda.setLista(listaInicial);
                listaFinal.addAll(busqueda.ejecutarEstrategia(nombre, null, null, null, null, null, cliente));
            }
            if (jRadioButtonCreador.isSelected())
            {
                String creador = (String) jComboBoxBusquedaCreador.getSelectedItem();
                estrategiaBusqueda = new EstrategiaBusquedaCreador();
                busqueda.setEstrategia(estrategiaBusqueda);
                busqueda.setLista(listaInicial);
                listaFinal.addAll(busqueda.ejecutarEstrategia(null, creador, null, null, null, null, cliente));
            }
            if (jRadioButtonValoracion.isSelected())
            {
                String valoracion = (String) jComboBoxBusquedaValGeneral.getSelectedItem();
                estrategiaBusqueda = new EstrategiaBusquedaValoracion();
                busqueda.setEstrategia(estrategiaBusqueda);
                busqueda.setLista(listaInicial);
                listaFinal.addAll(busqueda.ejecutarEstrategia(null, null, valoracion, null, null, null, cliente));
            }
            if (jRadioButtonPrecioMinimo.isSelected())
            {
                Double precioMinimo = (Double) jSpinnerPrecioMinimo.getValue();
                estrategiaBusqueda = new EstrategiaBusquedaPrecioMin();
                busqueda.setEstrategia(estrategiaBusqueda);
                busqueda.setLista(listaInicial);
                listaFinal.addAll(busqueda.ejecutarEstrategia(null, null, null, precioMinimo, null, null, cliente));
            }
            if (jRadioButtonPrecioMaximo.isSelected())
            {
                Double precioMaximo = (Double) jSpinnerPrecioMaximo.getValue();
                estrategiaBusqueda = new EstrategiaBusquedaPrecioMax();
                busqueda.setEstrategia(estrategiaBusqueda);
                busqueda.setLista(listaInicial);
                listaFinal.addAll(busqueda.ejecutarEstrategia(null, null, null, null, precioMaximo, null, cliente));
            }
            if (jRadioButtonTipo.isSelected())
            {
                String tipo = (String) jComboBoxTipo.getSelectedItem();
                estrategiaBusqueda = new EstrategiaBusquedaTipo();
                busqueda.setEstrategia(estrategiaBusqueda);
                busqueda.setLista(listaInicial);
                listaFinal.addAll(busqueda.ejecutarEstrategia(null, null, null, null, null, tipo, cliente));
            }
        }
        mt.setRowCount(0);
        ArrayList<Producto> listaMostrar = new ArrayList<>(); 
        for (Producto p: listaFinal)
        {
            if (!listaMostrar.contains(p))
            {
                listaMostrar.add(p);
            }
        }
        for (Producto p: listaMostrar)
        {
            if (p instanceof Videojuego)
            {
                mt.addRow(new Object[]{p.getNombre(), p.getCreador().getCorreo(), p.getValoracionGeneral(), p.getPrecio(cliente), "Videojuego", p.getCondigoInterno()});
            }
            else if (p instanceof Productividad)
            {
                mt.addRow(new Object[]{p.getNombre(), p.getCreador().getCorreo(), p.getValoracionGeneral(), p.getPrecio(cliente), "Productividad", p.getCondigoInterno()});
            }
            else
            {
                mt.addRow(new Object[]{p.getNombre(), p.getCreador().getCorreo(), p.getValoracionGeneral(), p.getPrecio(cliente), "Antivirus", p.getCondigoInterno()});
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonVerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerProductoActionPerformed
        String codigoProducto = (String) mt.getValueAt(jTableTienda.getSelectedRow(), 5);
        Producto producto = proxy.getProductoByCodigo(codigoProducto);
        ClienteInfoProducto cip = new ClienteInfoProducto(this, cliente, producto);
        this.setVisible(false);
        cip.setVisible(true);
    }//GEN-LAST:event_jButtonVerProductoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonVerProducto;
    private javax.swing.JComboBox<String> jComboBoxBusquedaCreador;
    private javax.swing.JComboBox<String> jComboBoxBusquedaValGeneral;
    private javax.swing.JComboBox<String> jComboBoxCriterio;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemLibreria;
    private javax.swing.JMenuItem jMenuItemLlavero;
    private javax.swing.JMenuItem jMenuItemNotificacion;
    private javax.swing.JMenuItem jMenuItemSaldo;
    private javax.swing.JMenuItem jMenuItemTienda;
    private javax.swing.JRadioButton jRadioButtonCreador;
    private javax.swing.JRadioButton jRadioButtonNombre;
    private javax.swing.JRadioButton jRadioButtonPrecioMaximo;
    private javax.swing.JRadioButton jRadioButtonPrecioMinimo;
    private javax.swing.JRadioButton jRadioButtonTipo;
    private javax.swing.JRadioButton jRadioButtonValoracion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPrecioMaximo;
    private javax.swing.JSpinner jSpinnerPrecioMinimo;
    private javax.swing.JTable jTableTienda;
    private javax.swing.JTextField jTextFieldBusquedaNombre;
    // End of variables declaration//GEN-END:variables
}
